spring:
  application:
    name: scheduler
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:17254/NEAR
    username: root
    password: test

swyp:
  firebase:
    key-path: 'static/firebase.json'
    url: 'https://fcm.googleapis.com/v1/projects/near-3cbf4'
